name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to docker registry
      run: docker login -u $USER -p $PASSWORD diamond.u-gakugei.ac.jp
      env:
        USER: ${{ secrets.DIAMOND_REGISTRY_USER }}
        PASSWORD: ${{ secrets.DIAMOND_REGISTRY_PASSWORD }}

    - name: Docker build cathe
      env:
          DOCKER_BUILDKIT: 1 # 必ず必要
      run: |
        docker build -t diamond.u-gakugei.ac.jp/springwork2000g0_app:latest --cache-from=diamond.u-gakugei.ac.jp/springwork2000g0_app:latest --build-arg BUILDKIT_INLINE_CACHE=1 -f docker/production/java/Dockerfile .
        docker build -t diamond.u-gakugei.ac.jp/springwork2000g0_db:latest --cache-from=diamond.u-gakugei.ac.jp/springwork2000g0_db:latest --build-arg BUILDKIT_INLINE_CACHE=1 -f docker/production/mysql/Dockerfile .
    - name: Push docker image
      run: |
        docker push diamond.u-gakugei.ac.jp/springwork2000g0_app:latest
        docker push diamond.u-gakugei.ac.jp/springwork2000g0_db:latest
